# set up
remote_theme: poole/lanyon
title: Mathematical Humanities Lab
description: Feel free to bookmark this to keep an eye on our project updates
url: http://fudab.github.io
baseurl: ''
paginate: 5
permalink: pretty

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version: 1.1.0
